name: personal_training
description: "A project to help you healty"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.0.1
  flutter_bloc: ^8.0.1
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.4

  cloud_firestore: ^5.5.0
  modal_progress_hud_nsn: ^0.5.0
  flutter_svg: ^2.0.13
  form_field_validator: ^1.1.0
  cached_network_image: ^3.4.0
  shared_preferences: ^2.3.4
  http: ^1.2.2
  toastification: ^2.3.0


  image_picker: ^1.1.0

  # Page View dots indicator
  dots_indicator: ^2.0.0

  # Percent circle
  percent_indicator: ^3.0.1

  # URL launcher
  url_launcher: ^6.0.9

  # Workout Details sliding up panel
  sliding_up_panel: ^2.0.0+1

  # Video player
  video_player: ^2.1.12

  # Countdown timer
  custom_timer: ^0.0.6




  cupertino_icons: ^1.0.8
  chewie: ^1.8.5
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/illustration/
    - assets/images/
    - assets/video/

fonts:
  - family: Raleway
    fonts:
      - asset: assets/fonts/Raleway/Raleway-Regular.ttf
      - asset: assets/fonts/Raleway/Raleway-Medium.ttf
        weight: 500
      - asset: assets/fonts/Raleway/Raleway-Bold.ttf
        weight: 700
      - asset: assets/fonts/Raleway/Raleway-Italic.ttf
        style: italic



